name: GitHub Actions Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: pwd

      - run: dir

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      - run: terraform version
